version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/lib

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm ci

      - run:
          name: "Lint check: JS"
          command: npm run lint

      - run:
          name: "Tests: unit-tests"
          command: npm run test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


workflows:
  version: 2
  test:
    jobs:
      - test
